(module
(func $main (result f64)
(call $fac(f64.const 7))
)
(func $fac(param $x f64) (result f64)
(if (f64.lt (get_local $x)(f64.const 1))
(then (set_local $x(f64.const 1))
)
(else (set_local $x(f64.mul (get_local $x)(call $fac(f64.sub (get_local $x)(f64.const 1)))))
))
(get_local $x)
)
(export "main" (func $main))
)