(module
  (func $main (result f64)
    (call $fac (f64.const 6))
  )
  (func $fac(param $x f64)  (result f64)
    (local $y f64)
    (if (f64.lt (get_local $x)(f64.const 1))
    (then (set_local $x (f64.const 1)))
    (else (set_local $y (f64.sub (get_local $x)(f64.const 1)))
    (set_local $x (f64.mul (get_local $x)(call $fac (get_local $y))))))
    (get_local $x)
  )
  (export "main" (func $main))
)
