(module
(func $main (result f64)
(call $fib (f64.const 30))
)
(func $fib(param $x f64)  (result f64)
(local $y f64)
(local $z f64)
(if (f64.le (get_local $x)(f64.const 2))
(then (set_local $x(f64.const 1)))
(else (set_local $y(f64.sub (get_local $x)(f64.const 1)))
(set_local $z(f64.sub (get_local $x)(f64.const 2)))
(set_local $x(f64.add (call $fib(get_local $y) )(call $fib(get_local $z))))))
(get_local $x)
)
(export "main" (func $main))
)